name: CI Pipeline with Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pytest

      - name: Run tests
        run: |
          python -m unittest test_addition.py

      - name: Archive code as artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-code
          path: |
            addition.py
            test_addition.py
